stylesheets:
  admin:
    - 'public/stylesheets/admin/admin.css'
  admin_ie:
    - 'public/stylesheets/admin/admin-ie.css'
  website:
    - 'public/stylesheets/reset.css'
    - 'public/stylesheets/screen.css'
  website_ie6:
    - 'public/stylesheets/ie6.css'
javascripts:
  admin:
    - 'public/javascripts/lib/modernizr.js'
    - 'public/javascripts/lib/selectivzr.js'
    - 'public/javascripts/lib/jquery.js'
    - 'public/javascripts/lib/jquery-ui.js'
    - 'public/javascripts/lib/jquery_ujs.js'
    - 'public/javascripts/lib/plugins/jquery.equalHeight.js'
    - 'public/javascripts/admin.js'
  website:
    - 'public/javascripts/application.js'

